[workspace]
members = ["packages/*"]

[workspace.package]
authors    = ["larry <gm@larry.engineer>"]
edition    = "2021"
homepage   = "https://larry.engineer"
repository = "https://github.com/steak-enjoyers/cw-plus-plus"
license    = "AGPL-3.0-or-later"
keywords   = ["cosmos", "cosmwasm"]

[workspace.dependencies]
cosmwasm-schema = "1.1"
cosmwasm-std    = "1.1"
cw-storage-plus = "1.0"
cw-utils        = "1.0"
proc-macro2     = "1"
quote           = "1"
schemars        = "0.8"
serde           = { version = "1", default-features = false }
syn             = "1"
thiserror       = "1"
